export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';


export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST'
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS'
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL'

export const GET_DETAILS_RESET = 'GET_DETAILS_RESET'
export const REJECTION_PRODUCT = 'REJECTION_PRODUCT'

export const AUTHENTIFICATED = 'AUTHENTIFICATED'
export const NON_AUTHENTIFICATED = 'NON_AUTHENTIFICATED'

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const API_URL = process.env.REACT_APP_SERVER_URL
export const PRODUCT_PRIFIX='/api/product'
export const USER_PRIFIX='/api/user'
export const AUTH_PRIFIX= '/api/auth'
export const EMAIL_PRIFIX= '/api/email'

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const  USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const CONTACT_US = 'CONTACT_US'
export const SAVE_QTTY_NUMBER_TOTAL ='SAVE_QTTY_NUMBER_TOTAL'
export const INCREMENTlIKES = 'INCREMENTlIKES'
export const COUNT_VISITORS = 'COUNT_VISITORS'

export const ADD_COMMENT = 'ADD_COMMENT'
export const FETCH_COMMENTS = 'FETCH_COMMENTS'